{% set name = "matplotlib2tikz" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 391eeec6c57c7e59d701e675ca513a292f7bb14f272ecf98bef88daa4d772d9f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib >=1.4.0
    - numpy
    - pillow
    - six

test:
  imports:
    - matplotlib2tikz
    - matplotlib2tikz.axes
    - matplotlib2tikz.color
    - matplotlib2tikz.files
    - matplotlib2tikz.image
    - matplotlib2tikz.legend
    - matplotlib2tikz.line2d
    - matplotlib2tikz.patch
    - matplotlib2tikz.path
    - matplotlib2tikz.quadmesh
    - matplotlib2tikz.save
    - matplotlib2tikz.text

about:
  home: https://github.com/nschloe/matplotlib2tikz
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'convert matplotlib figures into TikZ/PGFPlots'
  dev_url: https://github.com/nschloe/matplotlib2tikz

extra:
  recipe-maintainers:
    - m-rossi
