{% set name = "matplotlib2tikz" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: add08d7de4a2997f194b1c710d93b383bf3afed6b33e44e40589990798d8984d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3
    - matplotlib >=1.4.0
    - numpy
    - pillow
    - six

test:
  imports:
    - matplotlib2tikz
    - matplotlib2tikz.axes
    - matplotlib2tikz.color
    - matplotlib2tikz.files
    - matplotlib2tikz.image
    - matplotlib2tikz.legend
    - matplotlib2tikz.line2d
    - matplotlib2tikz.patch
    - matplotlib2tikz.path
    - matplotlib2tikz.quadmesh
    - matplotlib2tikz.save
    - matplotlib2tikz.text
    - matplotlib2tikz.util

about:
  home: https://github.com/nschloe/matplotlib2tikz
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'convert matplotlib figures into TikZ/PGFPlots'
  dev_url: https://github.com/nschloe/matplotlib2tikz

extra:
  recipe-maintainers:
    - m-rossi
