travis:
  secure:
    BINSTAR_TOKEN: Elo3yAO86zQsRC//lbSdtx0HgbKop5qhHFNJEoP2payA3nUVsc13y3ZQE473fekpwTMB4Q1uc32Jf4k1GHydgewfeKPPRa6bxiPwVCtKyyyiKOp4XoKkcq9kzIvgx90U1ucpKnfGqXFrXwObsmtegQzOdj2M9gTkcujXCkw69azxWHkvt99zGWhbw+4GiZgn58dRB/fFfC0EX5OrB6H1FK4BVzcwBo6rRrWDc5jV/6jpi4XnJjbwM0UxY0lQY0DegkxfVFwDnd/DIY7mn6qUJanLxwsTazCjTEDlP3YSjwiIPDtay6c+FuZwJpWgzpOFASghid5N8wSpqUQvcsoQoJ6zMuYtggvH8+u34TZTjSNYpm9HpEo00eW8WGKIZfNhmq7sMXfqX/D/IQx/pleU1n50uvDd0n5ZoLdpx+35JfYtS7a7eENj9pOyPBiTzdzpJYzZf1oq4SENf9bvzOxCe+v0mv9xVB7U5eDPYw31bVjIchBYKWeiWf0PMco26N8T+Wm1b7r3iKlM3DYhpHeqI5fjDrBmazd2pcIgYZ6rP8DWo6s9mLE74XIPM1ZwTkg2q1LVc6RkuYSsXRRij9/nDHhcTK5EPwNUovK+3H1olOchCiNlfT5Mi/e7NB5U5jaHynJVEjVZtVo6NRvWcuxzLcqlfgGBS/K002c4Prizqtc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
